config/routes.rb
Rails.application.routes.draw do
  root to: "links#index"

  mount GovukPublishingComponents::Engine, at: "/component-guide"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response(
    GovukHealthcheck::ActiveRecord,
    GovukHealthcheck::Redis,
  )

  resources "local_authorities", only: %i[index show update], param: :local_authority_slug do
    member do
      get "download_links_form"
      post "download_links_csv"
      get "upload_links_form"
      post "upload_links_csv"
      get "edit_url"
    end
  end

  resources "services", only: %i[index show], param: :service_slug do
    member do
      get "download_links_form"
      post "download_links_csv"
      get "upload_links_form"
      post "upload_links_csv"
      get "update-owner-form"
      patch "update-owner"
    end
  end

  get "/local_authorities/:local_authority_slug/services/:service_slug", to: redirect("/local_authorities/%{local_authority_slug}")

  scope "/local_authorities/:local_authority_slug/services/:service_slug" do
    resource ":interaction_slug", only: %i[edit update destroy], controller: "links", as: "link"
  end

  get "/check_homepage_links_status.csv", to: "links#homepage_links_status_csv"
  get "/check_links_status.csv", to: "links#links_status_csv"

  get "/bad_links_url_status.csv", to: "links#bad_links_url_and_status_csv"

  get "/bad_homepage_url_status.csv", to: "local_authorities#bad_homepage_url_and_status_csv"

  get "/api/link", to: "api#link"

  get "/api/local-authority", to: "api#local_authority"

  post "/link-check-callback", to: "webhooks#link_check_callback", as: :link_checker_webhook
end

app/models/service.rb
class Service < ApplicationRecord
  validates :lgsl_code, :label, :slug, presence: true, uniqueness: true

  has_many :service_interactions, dependent: :destroy
  has_many :links, through: :service_interactions
  has_many :interactions, through: :service_interactions
  has_many :service_tiers, dependent: :destroy
  has_many :local_authorities, through: :service_tiers

  scope :enabled, -> { where(enabled: true) }

  VALID_TIERS = ["district/unitary", "county/unitary", "all"].freeze

  def tiers
    service_tiers.pluck(:tier_id).map { |t_id| Tier.as_string(t_id) }
  end

  def update_broken_link_count
    update(broken_link_count: Link.for_service(self).broken_or_missing.count)
  end

  def valid_tier?(tier)
    VALID_TIERS.include?(tier)
  end

  def delete_and_create_tiers(tier_name)
    delete_all_tiers
    ServiceTier.create_tiers(required_tiers(tier_name), self)
  end

  def delete_all_tiers
    service_tiers.destroy_all
  end

  def required_tiers(tier_name)
    case tier_name
    when "district/unitary"
      [Tier.district, Tier.unitary]
    when "county/unitary"
      [Tier.county, Tier.unitary]
    when "all"
      [Tier.district, Tier.unitary, Tier.county]
    end
  end

  def to_param
    slug
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  include LinkFilterHelper
  include LinkImporterUtils

  before_action :set_service, except: :index

  before_action :forbid_unless_permission, only: %i[show download_links_form download_links_csv upload_links_form upload_links_csv]
  before_action :forbid_unless_gds_editor, only: %i[update_owner_form update_owner]

  helper_method :org_name_for_current_user

  def index
    @services = services_for_user(current_user).enabled.order(broken_link_count: :desc)

    @breadcrumbs = index_breadcrumbs
  end

  def show
    set_filter_var
    @link_filter = params[:filter]
    @links = links_for_service
    @breadcrumbs = service_breadcrumbs(@service)
  end

  def update_owner_form
    @breadcrumbs = service_breadcrumbs(@service) + [{ title: "Update Owner", url: update_owner_form_service_path(@service) }]
  end

  def update_owner
    @service.update!(organisation_slugs: params["service"]["organisation_slugs"].split(" "))

    redirect_to service_path(@service, filter: "broken_links")
  end

  def download_links_form
    @breadcrumbs = service_breadcrumbs(@service) + [{ title: "Download Links", url: download_links_form_service_path(@service) }]
  end

  def download_links_csv
    service_name = @service.label.parameterize.underscore
    statuses = params[:links_status_checkbox] & %w[ok broken caution missing pending]
    data = LocalLinksManager::Export::ServiceLinksExporter.new.export_links(@service.id, statuses)
    send_data data, filename: "#{service_name}_links.csv"
  end

  def upload_links_form
    @breadcrumbs = service_breadcrumbs(@service) + [{ title: "Upload Links", url: upload_links_form_service_path(@service) }]
  end

  def upload_links_csv
    return redirect_to service_path(@service) if attempt_import(:service, @service)

    redirect_to(upload_links_form_service_path(@service))
  end

private

  def services_for_user(user)
    return Service.all if gds_editor?

    Service.where(":organisation_slugs = ANY(organisation_slugs)", organisation_slugs: user.organisation_slug)
  end

  def set_service
    @service = Service.find_by!(slug: params[:service_slug])
  end

  def links_for_service
    @links_for_service ||= filtered_links(@service.links)
      .includes(%i[interaction local_authority service_interaction])
      .where(local_authority: @service.local_authorities)
      .all
  end

  def index_breadcrumbs
    [{ title: "Home", url: root_path }, { title: "Services", url: services_path }]
  end

  def service_breadcrumbs(service)
    index_breadcrumbs + [{ title: service.label, url: service_path(service) }]
  end
end

app/views/services/_local_authority.html.erb
<% links_by_authority = @links[local_authority.id] %>
<% unless links_by_authority.blank? %>
  <%= render partial: "service_links_by_authority", locals: { local_authority: local_authority, links_by_authority: links_by_authority } %>
<% end %>

app/views/services/_service_links_by_authority.html.erb
<tr data-local-authority-id="<%= local_authority.id %>" class="header-row">
  <th class="name" colspan="4">
    <h3><%= link_to local_authority.name, local_authority %></h3>
  </th>
</tr>
<% first_link, *remaining_links = links_by_authority %>
<%= render "shared/link_table_row", link: ServiceLinkPresenter.new(first_link, view_context: self, first: true) %>
<% remaining_links.each do |link| %>
  <%= render "shared/link_table_row", link: ServiceLinkPresenter.new(link, view_context: self, first: false) %>
<% end %>

app/views/services/download_links_form.html.erb
<% title = "Download links for #{@service.label}" %>
<% form_path = download_links_csv_service_path(@service) %>

<% content_for :page_title, title %>

<%= render partial: "shared/download_links_form", locals: { form_path:, title: } %>

app/views/services/index.html.erb
<% title = gds_editor? ? "Services" : "Services for #{org_name_for_current_user}" %>
<% content_for :page_title, title %>

<% breadcrumb :services %>

<%= render "govuk_publishing_components/components/heading", {
  text: "#{title} (#{@services.count})",
  heading_level: 1,
  font_size: "l",
  margin_bottom: 5,
} %>

<% services_table_presenter = ServicesTablePresenter.new(@services, self) %>

<%= render "govuk_publishing_components/components/table", {
  filterable: true,
  label: "Filter Services",
  head: services_table_presenter.headers,
  rows:  services_table_presenter.rows,
} %>

app/views/services/show.html.erb
<% content_for :page_title, @service.label %>
<%= render partial: "shared/flash" %>

<%= render "govuk_publishing_components/components/heading", {
  text: @service.label,
  heading_level: 1,
  font_size: "l",
  margin_bottom: 5,
} %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "govuk_publishing_components/components/summary_list", ServicePresenter.new(@service).summary_list(self) %>
  </div>
  <div class="govuk-grid-column-one-third">
    <aside class="app-side__wrapper">
      <div class="app-side">
        <div class="app-side__actions">
          <%
            items = []
            items << link_to("Update Owner", update_owner_form_service_path(@service), class: "govuk-link") if gds_editor?
            items << link_to("Download Links", download_links_form_service_path(@service), class: "govuk-link")
            items << link_to("Upload Links", upload_links_form_service_path(@service), class: "govuk-link")
            items << link_to(@filter_var == "broken_links" ? "Show only broken links" : "Show all links", service_path(@service.slug, filter: @filter_var), class: "govuk-link")
          %>
          <%= render "govuk_publishing_components/components/list", {
            items:,
            margin_bottom: 0,
          } %>
        </div>
      </div>
    </aside>
  </div>
</div>

<%= render partial: "shared/links_table", locals: { links_table_presenter: LinksTablePresenter.new(@links, self, remove_service: true) } %>

app/views/services/update_owner_form.html.erb
<% content_for :page_title, "Update Owner" %>

<%= render "govuk_publishing_components/components/heading", {
  text: "Update Owner",
  heading_level: 1,
  font_size: "l",
  margin_bottom: 5,
} %>

<%= form_for(@service, url: update_owner_service_path(@service)) do %>
  <%= render "govuk_publishing_components/components/input", {
    label: { text: "Organisation Slugs" },
    hint: "For multiple owning organisations, list slugs separated by spaces",
    name: "service[organisation_slugs]",
    value: @service&.organisation_slugs,
  } %>
  <%= render "govuk_publishing_components/components/button", { text: "Submit" } %>
  <%= render "govuk_publishing_components/components/button", {
    text: "Cancel",
    secondary_quiet: true,
    href: service_path(@service, filter: "broken_links"),
  } %>
<% end %>

app/views/services/upload_links_form.html.erb
<% title = "Upload links for #{@service.label}" %>
<% form_path = upload_links_csv_service_path(@service) %>

<% content_for :page_title, title %>

<%= render partial: "shared/flash" %>
<%= render partial: "shared/upload_links_form", locals: { form_path:, title: } %>