config/routes.rb
Rails.application.routes.draw do
  root to: "links#index"

  mount GovukPublishingComponents::Engine, at: "/component-guide"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response(
    GovukHealthcheck::ActiveRecord,
    GovukHealthcheck::Redis,
  )

  resources "local_authorities", only: %i[index show update], param: :local_authority_slug do
    member do
      get "download_links_form"
      post "download_links_csv"
      get "upload_links_form"
      post "upload_links_csv"
      get "edit_url"
    end
  end

  resources "services", only: %i[index show], param: :service_slug do
    member do
      get "download_links_form"
      post "download_links_csv"
      get "upload_links_form"
      post "upload_links_csv"
      get "update-owner-form"
      patch "update-owner"
    end
  end

  get "/local_authorities/:local_authority_slug/services/:service_slug", to: redirect("/local_authorities/%{local_authority_slug}")

  scope "/local_authorities/:local_authority_slug/services/:service_slug" do
    resource ":interaction_slug", only: %i[edit update destroy], controller: "links", as: "link"
  end

  get "/check_homepage_links_status.csv", to: "links#homepage_links_status_csv"
  get "/check_links_status.csv", to: "links#links_status_csv"

  get "/bad_links_url_status.csv", to: "links#bad_links_url_and_status_csv"

  get "/bad_homepage_url_status.csv", to: "local_authorities#bad_homepage_url_and_status_csv"

  get "/api/link", to: "api#link"

  get "/api/local-authority", to: "api#local_authority"

  post "/link-check-callback", to: "webhooks#link_check_callback", as: :link_checker_webhook
end

app/models/link.rb
class Link < ApplicationRecord
  before_update :set_link_check_results_on_updated_link, if: :url_changed?
  before_create :set_link_check_results_on_new_link

  belongs_to :local_authority, touch: true
  belongs_to :service_interaction, touch: true

  has_one :service, through: :service_interaction
  has_one :interaction, through: :service_interaction

  validates :local_authority, :service_interaction, presence: true
  validates :service_interaction_id, uniqueness: { scope: :local_authority_id }
  validates :url, non_blank_url: true

  scope :for_service,
        lambda { |service|
          includes(service_interaction: %i[service interaction])
            .references(:service_interactions)
            .where(service_interactions: { service_id: service })
        }

  scope :with_url, -> { where.not(url: nil) }
  scope :without_url, -> { where(url: nil) }

  scope :ok, -> { where(status: "ok") }
  scope :broken, -> { where(status: "broken") }
  scope :caution, -> { where(status: "caution") }
  scope :missing, -> { where(status: "missing") }
  scope :pending, -> { where(status: "pending") }
  scope :broken_or_missing, -> { broken.or(missing) }

  scope :last_checked_before,
        lambda { |last_checked|
          where("link_last_checked IS NULL OR link_last_checked < ?", last_checked)
        }

  validates :status, inclusion: { in: %w[ok broken caution missing pending] }, allow_nil: true

  def self.enabled_links
    joins(:service).where(services: { enabled: true })
  end

  def self.retrieve_or_build(params)
    joins(:local_authority, :service, :interaction).find_by(
      local_authorities: { slug: params[:local_authority_slug] },
      services: { slug: params[:service_slug] },
      interactions: { slug: params[:interaction_slug] },
    ) || build(params)
  end

  def self.lookup_by_service_and_interaction(service, interaction)
    with_url.joins(:service, :interaction).find_by(
      services: { id: service.id },
      interactions: { id: interaction.id },
    )
  end

  def self.lookup_by_base_path(base_path)
    govuk_slug, local_authority_slug = base_path[1..].split("/")

    joins(:local_authority, :service_interaction)
      .find_by(local_authorities: { slug: local_authority_slug },
               service_interactions: { govuk_slug: })
  end

  def self.build(params)
    Link.new(
      local_authority: LocalAuthority.find_by(slug: params[:local_authority_slug]),
      service_interaction: ServiceInteraction.find_by(
        service: Service.find_by(slug: params[:service_slug]),
        interaction: Interaction.find_by(slug: params[:interaction_slug]),
      ),
    )
  end

  def make_missing
    self.url = nil
    save!
  end

private

  def link_with_matching_url
    existing_link || existing_homepage
  end

  def existing_link
    @existing_link ||= Link.find_by(url:)
  end

  def existing_homepage
    @existing_homepage ||= LocalAuthority.find_by(homepage_url: url)
  end

  def set_link_check_results_on_updated_link
    if url.nil?
      update_columns(
        status: "missing",
        link_last_checked: nil,
        link_errors: [],
        link_warnings: [],
        problem_summary: nil,
        suggested_fix: nil,
      )
    elsif link_with_matching_url
      set_link_check_results(link_with_matching_url)
    else
      update_columns(
        status: nil,
        link_last_checked: nil,
        link_errors: [],
        link_warnings: [],
        problem_summary: nil,
        suggested_fix: nil,
      )
    end
  end

  def set_link_check_results_on_new_link
    set_link_check_results(link_with_matching_url) if link_with_matching_url
  end

  def set_link_check_results(link)
    self.status = link.status
    self.link_errors = link.link_errors
    self.link_warnings = link.link_warnings
    self.link_last_checked = link.link_last_checked
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :load_dependencies, only: %i[edit update destroy]
  before_action :set_back_url_before_post_request, only: %i[edit update destroy]

  before_action :forbid_unless_permission, only: %i[edit update]
  before_action :forbid_unless_gds_editor, only: %i[destroy homepage_links_status_csv links_status_csv bad_links_url_and_status_csv]
  before_action :redirect_unless_gds_editor, only: %i[index]

  helper_method :back_url

  def index
    currently_broken = Link.enabled_links.broken_or_missing
    @total_broken_links = currently_broken.count
    @broken_links = currently_broken.order(analytics: :desc).limit(200)
    @breadcrumbs = [{ title: "Home", url: "/" }]
  end

  def edit
    if flash[:link_url]
      @link.url = flash[:link_url]
      @link.validate
    end

    @breadcrumbs = [{ title: "Home", url: "/" }, { title: "Edit Link", url: request.path }]
  end

  def update
    @link.url = link_url
    @link.title = params[:title]

    if @link.save
      @link.local_authority.update_broken_link_count
      @link.service.update_broken_link_count
      redirect
    else
      flash[:danger] = "Please enter a valid link."
      redirect_back
    end
  end

  def destroy
    @link.make_missing
    redirect("deleted")
  end

  def homepage_links_status_csv
    data = LocalLinksManager::Export::LinkStatusExporter.homepage_links_status_csv
    send_data data, filename: "homepage_links_status.csv"
  end

  def links_status_csv
    data = LocalLinksManager::Export::LinkStatusExporter.links_status_csv
    send_data data, filename: "links_status.csv"
  end

  def bad_links_url_and_status_csv
    data = LocalLinksManager::Export::BadLinksUrlAndStatusExporter.bad_links_url_and_status_csv
    send_data data, filename: "bad_links_url_status.csv"
  end

private

  def load_dependencies
    @local_authority = LocalAuthority.find_by!(slug: params[:local_authority_slug])
    @interaction = Interaction.find_by!(slug: params[:interaction_slug])
    @service = Service.find_by!(slug: params[:service_slug])
    @link = Link.retrieve_or_build(params)
  end

  def set_back_url_before_post_request
    flash[:back] = back_url
  end

  def back_url
    flash[:back] ||
      request.env["HTTP_REFERER"] ||
      local_authority_path(local_authority_slug: params[:local_authority_slug])
  end

  def link_url
    params[:url].strip
  end

  def redirect_back
    flash[:link_url] = link_url
    redirect_to edit_link_path(@local_authority, @service, @interaction)
  end

  def redirect(action = "saved")
    flash[:success] = "Link has been #{action}."
    flash[:updated] = { url: @link.url, lgil: @interaction.lgil_code }
    redirect_to back_url
  end
end

app/views/links/_link_status_alerts.html.erb
<% pres = LinkPresenter.new(link) %>
<% last_message = alerts.pop %>
<%= render "govuk_publishing_components/components/inset_text", {
} do %>
  <div>
  <% alerts.each do |message| %>
    <p class="govuk-body"> <span class="govuk-tag govuk-tag--<%= pres.status_tag_colour %>"><%= pres.status_description %>:</span> <%= message %></p>
  <% end %>
  <p class="govuk-body <%= "govuk-!-margin-bottom-0" unless link.suggested_fix? %>"> <span class="govuk-tag govuk-tag--<%= pres.status_tag_colour %>"><%= pres.status_description %>:</span> <%= last_message %></p>

  <% if link.suggested_fix? %>
    <p class="govuk-body govuk-!-margin-bottom-0">Suggested fix: <%= link.suggested_fix %></p>
  <% end %>
</div>
<% end %>

app/views/links/_link_table_row.html.erb
<%= content_tag "tr",
    class: link.updated? ? "success" : "",
    data: link.row_data do %>
  <td class="analytics"><span><%= link.analytics.to_i %></span>visits this week</td>
  <td class="links">
    <div class="local-authority"><%= link.local_authority.name %></div>
    <div class="govuk"><%= link.govuk_title || link.service_label %>
      <span class='code'>code: <%= link.service_interaction.lgsl_code %></span>
    </div>
    <div class="detail-links">
      <a href="https://www.gov.uk/<%= link.service_interaction.govuk_slug %>">GOV.UK</a> &rarr;
      <% if link.url %>
        <%= link_to truncate(link.url, length: 80), link.url %>
      <% else %>
        <%= link_to "No URL", link.local_authority.homepage_url %>
      <% end %>
    </div>
  </td>
  <td class="status text-right">
    <div class="<%= link.label_status_class %>">
        <b><%= link.status_description %></b>
    </div>
    <span><%= link.last_checked %></span>
  </td>
  <td class="text-center">
    <%= link_to("Edit link", link.edit_path, class: "btn btn-default btn-lg") %>
  </td>
<% end %>

app/views/links/edit.html.erb
<% content_for :page_title, "Editing #{ @local_authority.name } - #{ @service.label} - #{@interaction.label}" %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">

    <%= render "govuk_publishing_components/components/heading", {
      text: "Editing #{@local_authority.name} - #{ @service.label} - #{@interaction.label}",
      heading_level: 1,
      font_size: "l",
      margin_bottom: 5,
    } %>

    <% if @link.link_errors.any? %>
      <%= render partial: "link_status_alerts", locals: { alerts: @link.link_errors, link: @link } %>
    <% elsif @link.link_warnings.any? %>
      <%= render partial: "link_status_alerts", locals: { alerts: @link.link_warnings, link: @link } %>
    <% end %>

    <%= form_for @link, url: link_path(@local_authority.slug, @service.slug, @interaction.slug), method: "put" do |f| %>

      <%= render "govuk_publishing_components/components/input", {
        label: {
          text: "Page URL",
        },
        name: "url",
        hint: "for example https://www.local-authority.gov.uk/my-service",
        autofocus: true,
        tabindex: 0,
        value: @link.url,
      } %>

      <%= render "govuk_publishing_components/components/input", {
        label: {
          text: "Link Title (optional)",
        },
        name: "title",
        hint: "leave blank for default title",
        autofocus: true,
        tabindex: 1,
        value: @link.title,
      } %>

      <%= render "govuk_publishing_components/components/button", { text: "Update" } %>
    <% end %>

    <% if @link.url && gds_editor? %>
      <div class="app-danger-block">
        <%= form_for @link, url: link_path(@local_authority.slug, @service.slug, @interaction.slug), method: "delete", data: { confirm: "Are you sure you wish to delete this link?" } do |f| %>
        <p class="govuk-body">You can also delete this link if you are certain it is no longer necessary (NB: this cannot be undone)</p>
        <%= render "govuk_publishing_components/components/button", {
            text: "Delete",
            destructive: true,
          } %>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/links/index.html.erb
<% content_for :page_title, "Broken Links" %>
<%= render partial: "shared/flash" %>

<%= render "govuk_publishing_components/components/heading", {
  text: "Broken Links (showing top 200 of #{@total_broken_links})",
  heading_level: 1,
  font_size: "l",
  margin_bottom: 5,
} %>

<%= render partial: "shared/links_table", locals: { links_table_presenter: LinksTablePresenter.new(@broken_links, self) } %>