config/routes.rb
Rails.application.routes.draw do
  root to: "links#index"

  mount GovukPublishingComponents::Engine, at: "/component-guide"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response(
    GovukHealthcheck::ActiveRecord,
    GovukHealthcheck::Redis,
  )

  resources "local_authorities", only: %i[index show update], param: :local_authority_slug do
    member do
      get "download_links_form"
      post "download_links_csv"
      get "upload_links_form"
      post "upload_links_csv"
      get "edit_url"
    end
  end

  resources "services", only: %i[index show], param: :service_slug do
    member do
      get "download_links_form"
      post "download_links_csv"
      get "upload_links_form"
      post "upload_links_csv"
      get "update-owner-form"
      patch "update-owner"
    end
  end

  get "/local_authorities/:local_authority_slug/services/:service_slug", to: redirect("/local_authorities/%{local_authority_slug}")

  scope "/local_authorities/:local_authority_slug/services/:service_slug" do
    resource ":interaction_slug", only: %i[edit update destroy], controller: "links", as: "link"
  end

  get "/check_homepage_links_status.csv", to: "links#homepage_links_status_csv"
  get "/check_links_status.csv", to: "links#links_status_csv"

  get "/bad_links_url_status.csv", to: "links#bad_links_url_and_status_csv"

  get "/bad_homepage_url_status.csv", to: "local_authorities#bad_homepage_url_and_status_csv"

  get "/api/link", to: "api#link"

  get "/api/local-authority", to: "api#local_authority"

  post "/link-check-callback", to: "webhooks#link_check_callback", as: :link_checker_webhook
end

app/models/local_authority.rb
class LocalAuthority < ApplicationRecord
  after_commit :update_external_content, if: :persisted?

  validates :gss, :slug, uniqueness: true
  validates :snac, uniqueness: true, allow_nil: true
  validates :gss, :name, :slug, presence: true
  validates :tier_id,
            presence: true,
            inclusion:
                {
                  in: [Tier.unitary, Tier.district, Tier.county],
                  message: "%{value} is not a valid tier",
                }

  has_many :links, dependent: :destroy
  belongs_to :parent_local_authority, class_name: "LocalAuthority", inverse_of: false, optional: true
  belongs_to :succeeded_by_local_authority, class_name: "LocalAuthority", inverse_of: false, optional: true
  has_many :service_tiers, foreign_key: :tier_id, primary_key: :tier_id, inverse_of: :local_authority, dependent: :restrict_with_error
  has_many :services, through: :service_tiers

  scope :link_last_checked_before,
        lambda { |last_checked|
          where("link_last_checked IS NULL OR link_last_checked < ?", last_checked)
        }

  scope :active, -> { where("active_end_date IS NULL OR active_end_date > ?", Time.zone.now) }

  validates :status, inclusion: { in: %w[ok broken caution pending] }, allow_nil: true

  def tier
    Tier.as_string(tier_id)
  end

  def provided_services
    services.enabled
  end

  # returns the Links for this authority,
  # for the enabled Services that this authority provides.
  def provided_service_links
    links.joins(:service).merge(provided_services)
  end

  def update_broken_link_count
    update(broken_link_count: provided_service_links.broken_or_missing.count)
  end

  def to_param
    slug
  end

  def active?
    active_end_date.nil? || (active_end_date > Time.zone.now)
  end

  def self.find_current_by_slug(slug)
    la = find_by(slug:)
    return nil unless la
    return la if la.active?

    la.succeeded_by_local_authority
  end

  def self.find_current_by_local_custodian_code(local_custodian_code)
    la = find_by(local_custodian_code:)
    return nil unless la
    return la if la.active?

    la.succeeded_by_local_authority
  end

private

  def update_external_content
    if active?
      LocalAuthorityExternalContentPublisher.new(self).publish if publishable_changes?
    else
      LocalAuthorityExternalContentPublisher.new(self).unpublish
    end
  end

  def publishable_changes?
    saved_change_to_name? || saved_change_to_homepage_url?
  end
end

app/controllers/local_authorities_controller.rb
class LocalAuthoritiesController < ApplicationController
  include LinkFilterHelper
  include LinkImporterUtils

  before_action :set_authority, except: %i[index bad_homepage_url_and_status_csv]

  before_action :forbid_unless_gds_editor, only: %i[update download_links_csv upload_links_csv bad_homepage_url_and_status_csv]
  before_action :redirect_unless_gds_editor, only: %i[index show edit_url download_links_form upload_links_form]

  def index
    Rails.logger.info(params)

    @authorities = if params[:filter]&.include?("only_active")
                     LocalAuthority.active.order(broken_link_count: :desc)
                   else
                     LocalAuthority.order(broken_link_count: :desc)
                   end

    @authorities = @authorities.where.not(status: "ok") if params[:filter]&.include?("only_homepage_problems")

    @breadcrumbs = index_breadcrumbs
  end

  def show
    set_filter_var
    @link_filter = params[:filter]
    @links = links_for_authority.includes(:service).order("services.label")
    @breadcrumbs = local_authority_breadcrumbs(@authority)
  end

  def edit_url
    @breadcrumbs = local_authority_breadcrumbs(@authority) + [{ title: "Edit URL", url: edit_url_local_authority_path(@authority) }]
  end

  def update
    @authority.update!(homepage_url: params[:homepage_url])

    redirect_to local_authority_path(@authority)
  end

  def download_links_form
    @breadcrumbs = local_authority_breadcrumbs(@authority) + [{ title: "Download Links", url: download_links_form_local_authority_path(@authority) }]
  end

  def download_links_csv
    authority_name = @authority.name.parameterize.underscore
    statuses = params[:links_status_checkbox] & %w[ok broken caution missing pending]
    data = LocalLinksManager::Export::LocalAuthorityLinksExporter.new.export_links(@authority.id, statuses)
    send_data data, filename: "#{authority_name}_links.csv"
  end

  def upload_links_form
    @breadcrumbs = local_authority_breadcrumbs(@authority) + [{ title: "Upload Links", url: upload_links_form_local_authority_path(@authority) }]
  end

  def upload_links_csv
    return redirect_to local_authority_path(@authority) if attempt_import(:local_authority, @authority)

    redirect_to(upload_links_form_local_authority_path(@authority))
  end

  def bad_homepage_url_and_status_csv
    data = LocalLinksManager::Export::BadLinksUrlAndStatusExporter.local_authority_bad_homepage_url_and_status_csv
    send_data data, filename: "bad_homepage_url_status.csv"
  end

private

  def set_authority
    @authority = LocalAuthority.find_by!(slug: params[:local_authority_slug])
  end

  def index_breadcrumbs
    [{ title: "Home", url: root_path }, { title: "Councils", url: local_authorities_path(filter: %w[only_active]) }]
  end

  def local_authority_breadcrumbs(local_authority)
    index_breadcrumbs + [{ title: local_authority.name, url: local_authority_path(local_authority) }]
  end

  def links_for_authority
    @links_for_authority ||= filtered_links(@authority.provided_service_links)
      .includes(%i[service interaction])
      .all
  end
end

app/views/local_authorities/_filter.html.erb
<%= form_with url: local_authorities_path, method: :get do |form| %>
  <%= render "govuk_publishing_components/components/option_select", {
    options_container_id: "list_of_vegetables",
    title: "Only show",
    key: "filter",
    options: [
      {
        value: "only_active",
        label: "Active councils",
        checked: params[:filter]&.include?("only_active"),
      },
      {
        value: "only_homepage_problems",
        label: "Homepage problems",
        checked: params[:filter]&.include?("only_homepage_problems"),
      },
    ],
  } %>

  <%= render "govuk_publishing_components/components/button", {
    text: "Update",
    margin_bottom: 4,
    data_attributes: {
      module: "gem-track-click",
      "track-category": "form-button",
      "track-action": "local-authority-filter-button",
      "track-label": "Update",
    },
  } %>
<% end %>

app/views/local_authorities/download_links_form.html.erb
<% title = "Download links for #{@authority.name}" %>
<% form_path = download_links_csv_local_authority_path(@authority) %>

<% content_for :page_title, title %>

<%= render partial: "shared/download_links_form", locals: { form_path:, title: } %>

app/views/local_authorities/edit_url.html.erb
<% content_for :page_title, "Editing #{@authority.name}" %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">

    <%= render "govuk_publishing_components/components/heading", {
      text: "Editing #{@authority.name}",
      heading_level: 1,
      font_size: "l",
      margin_bottom: 5,
    } %>

    <%= form_for(@authority) do %>
      <%= render "govuk_publishing_components/components/input", {
        label: {
          text: "Homepage URL",
        },
        name: "homepage_url",
        autofocus: true,
        tabindex: 0,
        value: @authority.homepage_url,
      } %>

      <%= render "govuk_publishing_components/components/button", { text: "Update" } %>
    <% end %>

  </div>
</div>

app/views/local_authorities/index.html.erb
<% content_for :page_title, "Councils" %>

<% breadcrumb :local_authorities %>

<%= render "govuk_publishing_components/components/heading", {
  text: "Councils (#{@authorities.count})",
  heading_level: 1,
  font_size: "l",
  margin_bottom: 5,
} %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-one-quarter">
    <%= render "filter" %>
  </div>

  <div class="govuk-grid-column-three-quarters">
    <% local_authorities_table_presenter = LocalAuthoritiesTablePresenter.new(@authorities, self) %>
    <%= render "govuk_publishing_components/components/table", {
      filterable: true,
      label: "Filter Council Names",
      head: local_authorities_table_presenter.headers,
      rows:  local_authorities_table_presenter.rows,
    } %>
  </div>
</div>

app/views/local_authorities/show.html.erb
<% content_for :page_title, @authority.name %>
<%= render partial: "shared/flash" %>

<%= render "govuk_publishing_components/components/heading", {
  text: @authority.name,
  heading_level: 1,
  font_size: "l",
  margin_bottom: 5,
} %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "govuk_publishing_components/components/summary_list", LocalAuthorityPresenter.new(@authority).summary_list(self) %>
  </div>
  <div class="govuk-grid-column-one-third">
    <aside class="app-side__wrapper">
      <div class="app-side">
        <div class="app-side__actions">
          <%= render "govuk_publishing_components/components/list", {
            items: [
              link_to("Edit Homepage URL", edit_url_local_authority_path(@authority), class: "govuk-link"),
              link_to("Download Links", download_links_form_local_authority_path(@authority), class: "govuk-link"),
              link_to("Upload Links", upload_links_form_local_authority_path(@authority), class: "govuk-link"),
              link_to(@filter_var == "broken_links" ? "Show only broken links" : "Show all links", local_authority_path(@authority.slug, filter: @filter_var), class: "govuk-link"),
            ],
            margin_bottom: 0,
          } %>
        </div>
      </div>
    </aside>
  </div>
</div>

<%= render partial: "shared/links_table", locals: { links_table_presenter: LinksTablePresenter.new(@links, self, remove_council: true) } %>

app/views/local_authorities/upload_links_form.html.erb
<% title = "Upload links for #{@authority.name}" %>
<% form_path = upload_links_csv_local_authority_path(@authority) %>

<% content_for :page_title, title %>

<%= render partial: "shared/flash" %>

<%= render partial: "shared/upload_links_form", locals: { form_path:, title: } %>